[workspace]
resolver = "3"
members = ["bindings"]

[workspace.package]
keywords = ["anoma", "evm", "protocol-adapter"]
authors = ["Anoma Foundation"]
license = "MIT"
repository = "https://github.com/anoma/evm-protocol-adapter"
homepage = "https://anoma.net/"
edition = "2024"
