[package]
name = "evm_protocol_adapter_bindings"
version = "1.0.0-rc.3"
edition = "2024"

[dependencies]
arm_risc0 = { git = "https://github.com/anoma/arm-risc0.git", tag = "v0.11.0", package = "arm", features = [
    "groth16_prover", # Add this feature to generate regular transactions. Note that proof aggregation won't work.
    "groth16_aggregation",
    "bonsai",
    "test",
] }
alloy = { version = "1.1.0", features = ["full", "eip712", "node-bindings"] }
alloy-chains = "0.2.18"

tokio = { version = "1.48", features = ["rt-multi-thread"] }
serde = { version = "1.0.228", default-features = false }

[dev-dependencies]
dotenv = { version = "0.15.0", features = ["cli"] }

[features]
# These features are enabled to generate test transactions and are not required for using the library.
arm_risc0_dev = ["arm_risc0/groth16_prover", "arm_risc0/bonsai"]
