[package]
description = "Anoma EVM protocol adapter bindings and contract deployments."
name = "anoma-pa-evm-bindings-test"
version = "1.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alloy = { version = "1.3.0", features = ["full", "eip712", "node-bindings"] }
alloy-chains = "0.2.24"
tokio = { version = "1.48", features = ["rt-multi-thread"] }
serde = { version = "1.0.228", default-features = false }
thiserror = "2.0.17"
anoma-rm-risc0-test-0112 = "1.0.0"
anoma-rm-risc0-test-app-test-0112 = "1.0.0"

dotenvy = { version = "0.15.7", features = ["cli"] }


#[features]
# These features are enabled to generate test transactions and are not required for using the library.
#arm_risc0_dev = ["arm_risc0/bonsai"]
