[package]
name = "evm_protocol_adapter_bindings"
version = "1.0.0-rc.2"
edition = "2024"

[dependencies]
arm_risc0 = { git = "https://github.com/anoma/arm-risc0.git", tag = "v0.8.1", package = "arm", features = [
    "groth16_prover", # Add this feature to generate regular transactions. Note that proof aggregation won't work.
    "groth16_aggregation",
    "bonsai",
    "test",
] }
alloy = { version = "1.0.30", features = ["full", "eip712", "node-bindings"] }
async-trait = "0.1.89"
tokio = { version = "1.44", features = ["rt-multi-thread"] }
serde = { version = "1.0.197", default-features = false }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false }

[features]
# These features are enabled to generate test transactions and is not required for using the library.
arm_risc0_dev = ["arm_risc0/groth16_prover", "arm_risc0/bonsai"]
