[package]
name = "evm_protocol_adapter_bindings"
version = "1.0.0-beta"
edition = "2024"

[dependencies]
arm_risc0 = { git = "https://github.com/anoma/arm-risc0.git", rev = "164edf283d32cbd537f82d925b1f3212efed6e13", package = "arm", features = [
    "groth16_prover",
    "bonsai"
] }
alloy = { version = "1.0.30", features = ["full", "eip712", "node-bindings"] }
tokio = "1.44"
serde = { version = "1.0.197", default-features = false }
sha2 = { version = "0.10.9" }
serde_json = "1.0.143"
hex = "0.4.3"

[dev-dependencies]
alloy-sol-types = "1.0.23"
simple_transfer_app = { git = "https://github.com/anoma/arm-risc0.git", rev = "164edf283d32cbd537f82d925b1f3212efed6e13", package = "simple-transfer-app" }

[features]
# These features are enabled to generate test transactions and is not required for using the library.
arm_risc0_dev = ["arm_risc0/groth16_prover", "arm_risc0/bonsai"]
