[package]
name = "evm_protocol_adapter_bindings"
version = "1.0.0-beta"
edition = "2024"

[dependencies]
arm_risc0 = { git = "https://github.com/anoma/arm-risc0.git", rev = "17af3dadd188e767f4affc6bf300f4426d4c741a", package = "arm", features = [
    "groth16_prover",
    "bonsai"
] }
alloy = { version = "1.0.30", features = ["full", "eip712", "node-bindings"] }
tokio = { version = "1.44", features = ["rt-multi-thread"] }
serde = { version = "1.0.197", default-features = false }
sha2 = { version = "0.10.9" }
simple_transfer_app = { git = "https://github.com/anoma/arm-risc0.git", rev = "17af3dadd188e767f4affc6bf300f4426d4c741a", package = "simple-transfer-app" }



[features]
# These features are enabled to generate test transactions and is not required for using the library.
arm_risc0_dev = ["arm_risc0/groth16_prover", "arm_risc0/bonsai"]
